# Development configuration overrides
log:
  handlers: [ErrorLogHandler, FirePHPHandler]
  level: DEBUG
  ##
  # Examples for configuring a log handler individually:
  #
  # handlers: [StreamHandler, ErrorLogHandler]
  # StreamHandler:
  #   stream: /path/to/my/log/or/streamaddress
  #   level: INFO
  # ErrorLogHandler:
  #   level: DEBUG
  #   error_log: 'default' or path
  ##
debug: true
